[toolchain]
channel = "nightly-2025-09-20"
components = ["rustfmt", "rust-src", "clippy", "llvm-tools"]
targets = [
    "aarch64-unknown-none",
    "riscv64gc-unknown-none-elf",
    "x86_64-unknown-none",
]
